### ISSUE TITLE
The example with Array(count).map does not work

### ISSUE THREAD

**Issue by moltar** [jeanfortheweb/typeorm-fixture-builder#16]
Althought it is clever, and I thought it'd work for sure, but spent a good amount of time hair ripping 😁 

```
export function createRandomUsers(count: number): User[] {
  return new Array(count).map(createRandomUser(()))
}
```

https://itnext.io/heres-why-mapping-a-constructed-array-doesn-t-work-in-javascript-f1195138615a

**Comment by jeanfortheweb** [comment]
This is correct, unfortunately. I made a mistake. The correct way would be: 

```
[...new Array(count)].map(user);
```

I will have to update it.

**Comment by jeanfortheweb** [comment]
It's finally fixed in the docs <3
