### ISSUE TITLE
Add option for disabling transactions

### ISSUE THREAD

**Issue by dustinsmith1024** [jeanfortheweb/typeorm-fixture-builder#19]
Every once in awhile I go into https://github.com/jeanfortheweb/typeorm-fixture-builder/blob/master/src/install.ts#L17 and turn off transactions. 

It helps when I don't want to wipe the database in between runs. Usually its because I am developing and messed up some of the data.

I can PR it if you are interested. Not sure if your continuing to dev on this.

**Comment by jeanfortheweb** [comment]
Sorry for not seeing your issue dustin!
Sure, handling of transactions could be a thing. Guess they should still run by default? Or the opposite by using --transactional?

Could be confusing for existing users who expect transactions to run

**Comment by jeanfortheweb** [comment]
Hey dustin, still interested on figuring out a good update for this? Can you show an example on how you solved it? I would like to make it meaningful for anyone.
