### ISSUE TITLE
CLI Pattern argument

### ISSUE THREAD

**Issue by peanutbother** [jeanfortheweb/typeorm-fixture-builder#25]
I'm using typeorm but I do compile my files before running and I don't want to use ts-node.
The problem is, that the clie is using the pattern `.bundle.ts` which is problematic when running fixtures using compiled files.

My proposal would be to introduce a CLI argument to allow custom search patterns for fixtures, something like 

`--pattern *.bundle.js`

this would be a cool feature since the only other way would be to use the programmatic api.

**Comment by jeanfortheweb** [comment]
Hello peanutbother!
Do you have any problems using a custom pattern? It should actuall work as argument, not as option, so just without --pattern
