### ISSUE TITLE
Async fixtures

### ISSUE THREAD

**Issue by harveyappleton** [jeanfortheweb/typeorm-fixture-builder#53]
Hey @jeanfortheweb 

Just a quick one, would it be possible for the cli to accept bundle files that have async fixtures? I'm using it with bundles as described here [https://github.com/jeanfortheweb/typeorm-fixture-builder#fixture-bundle-files](https://github.com/jeanfortheweb/typeorm-fixture-builder#fixture-bundle-files)

but it doesn't like fixtures that return promises.
Would that be an easy change?

Thanks!
H

**Comment by jeanfortheweb** [comment]
Hey harvey. Wonder first why you would need them. Do you generate fixtures from another async source?

**Comment by harveyappleton** [comment]
Hey @jeanfortheweb, yeh I have interdependant relations, so it would be amazing if the library could await my fixtures creating other entities/doing other things? I've been able to use this library for simple fixtures but not for complex ones.

**Comment by jeanfortheweb** [comment]
@harveyappleton surely im happy to see what makes sense, could you give a (pseudo) example?
