### ISSUE TITLE
Recursive loop when run inside of docker

### ISSUE THREAD

**Issue by harveyappleton** [jeanfortheweb/typeorm-fixture-builder#54]
Hey @jeanfortheweb 

Just came across a weird one. When I run the command on my local machine (`yarn fixtures install`) it works fine, but inside of docker it seems to connect to the database many times, and only installs 1 of the 4 bundles I have? Wonder if you have any ideas why this might be? Most of the time it causes the docker container to crash :( 

Thanks!
Harvey
![Screenshot 2021-08-05 at 14 12 02](https://user-images.githubusercontent.com/56404035/128355750-dd005c89-8e3d-4fd9-8a99-4e7c002454f4.png)

**Comment by jeanfortheweb** [comment]
Interesting one, im using it in containers all day. Could you show of your typeorm configuration?
