### ISSUE TITLE
Relation inserted twice

### ISSUE THREAD

**Issue by lukaswindisch** [jeanfortheweb/typeorm-fixture-builder#62]
Hi!
First of all I want to point out that you created a really nice npm package here!

I just have a problem with my fixtures when I try to reference a foreign key  with a fixture that has already been created:

```ts
const publicDic = fixture(DepositInsuranceCase, {
  name: 'XXXXX',
  createdAt: new Date(),
  createdBy: 'admin@xxx.at',
});

const customer = fixture(Customer, {
    depositInsuranceCase: publicDic,
    accountOwner: null,
    phoneNumber: null,
    postCode: 'XXXX',
  });
```

Those two fixtures are used in my application.

First I create the publicDic with the install method. After that I want to create the Customer that should reference this publicDic. When I call install on the customer object it tries to create the publicDic a second time. How can I prevent this from happening? 

Something that might be useful to know: The customer has a foreign Key that references one deposit insurance case. So it is a ManyToOne relation, seen from the customer's perspective.

Thank you and best regards,
Lukas

**Comment by jeanfortheweb** [comment]
Hello @lukaswindisch and thanks for your time. At the same time, sorry for my quite late response.
First of all, seen from your code, is any of these fixtures exported? In the best case scenario, you export them all. This will also ensure that each fixture will be correctly "marked as persisted".

In general, the cli will just walk over every fixture and if it finds one that has not been persisted yet, it will run the query and use the resulting id for the relation. It's actually quite simple.

If the problems persists, I would love to have some reproduction code or repository. Some entities and a bundle would be totally fine, even in a single code snippet.
