### ISSUE TITLE
Fixture with a resolver inside a fixture is not passing db constraint

### ISSUE THREAD

**Issue by davidyell** [jeanfortheweb/typeorm-fixture-builder#74]
## Env
Node 16.19.0
TypeORM 0.2.37
Fixture builder 2.2.3

## Setup
I have a table and it has a many to many join via a join table. I have created the fixtures for the main table, and other fixtures for the table which is joined, but I am struggling to write fixtures for the join table rows.

`Occasion -< OccasionOwnerType >- OwnerType`

## What I did
I would like to create a random amount of join row fixtures, based on what data is already in the `OwnerTypes` table. So I created my function which outputs an array of fixture objects for the join table, based on the `Occasions` fixture data, so I know what to join to.
As the db constraint fails if the join table doesn't have a valid `occasion_id`

```typescript
const buildJoinForOwnerTypeFixtures = (): OccasionOwnerType[] => {
  const ownerTypes: OwnerType['language_key'][] = ['owner_types.visit', 'owner_types.travel', 'owner_types.stipend', 'owner_types.participant', 'owner_types.expense', 'owner_types.claim'];

  const fixtures: OccasionOwnerType[] = [];

  occasionsFixtures.forEach(occasion => {
    const quantity = faker.datatype.number({ min: 0, max: ownerTypes.length });
    const pickedOwnerTypes = sampleSize(ownerTypes, quantity);

    if (pickedOwnerTypes.length > 0) {
      pickedOwnerTypes.forEach(ownerTypeKey => {
        fixtures.push(
          fixture(OccasionOwnerType, {
            uuid: faker.datatype.uuid(),
            owner_id: faker.datatype.uuid(),
            ownerType: fixture(OwnerType, { language_key: ownerTypeKey }, (repository, ownerTypeFixture) =>
              repository.createQueryBuilder('ownerType').where('ownerType.language_key = :key', { key: ownerTypeFixture.language_key })
            ),
            occasion: occasion
          })
        );
      });
    }
  });

  return fixtures;
};
```

## What happened?
The occasion fixtures are processed just fine, but I get an SQL error when trying to run the `OwnerType` fixture.

> QueryFailedError: Cannot add or update a child row: a foreign key constraint fails (`service-occasion-api`.`occasion_owner_types`, CONSTRAINT `FK_19534abd90222a238e7ea6ab052` FOREIGN KEY (`owner_type_id`) REFERENCES `owner_types` (`id`))

I thought that by adding the resolver function it would lookup the owner type from the data store? If I intentionally break the query builder with a bogus condition, for example, the fixture works, but it creates lots of new `OwnerType` records, which I do not need.

I would like to just join the relation to the fixture, rather than update it or create new ones.

Any thoughts or ideas would be great, thanks!

**Comment by davidyell** [comment]
Further investigation it seems that my resolver is not working and so the fixture is returned which has no primary key, and thus fails the constraint.

I have tested the query and it works to find the record in question, so I am confident the query is syntactically correct.

**Comment by davidyell** [comment]
Is it possible for me to just load the OwnerType entities from the database directly?

**Comment by jeanfortheweb** [comment]
Hi @davidyell im not completely sure about the issue already but what I can say is that, if the table i meant to be filled initially by the fixtures, there is no guarantee that they have been saved in the moment you ask for them, since there is no real order. The persister will save the entities in the order they have been collected and all relations he will find in between. However, you can work with the "local" fixture arrays before they get persisted to the database (before install), you just have to give them primary keys before hand if they are not generated.

**Comment by jeanfortheweb** [comment]
Another way i could imagine is to split your fixtures into two seperate bundles. Then you would be able to force an order of execution. As long as you dont clear the database in between these "dependend" bundles it should work fine.

**Comment by davidyell** [comment]
I have partially solved the issue by creating a single bundle which creates two sets of fixtures in the order that I needed. That worked for me.

I also then included the related fixtures from the other bundle, instead of using a resolver, and that solved the issue of the db constraint.

I will mark this as resolved now, as the fixture is working as I expected 👍
